### ISSUE TITLE
Feature Request: Parse dynamic placeholders for Scratchpad note path

### ISSUE THREAD

**Issue by DeLub** [chrisgrieser/shimmering-obsidian#110]
### Feature Requested

Please make it possible to use Alfred's dynamic placeholders in other variables like Scratchpad note path.

I'm aware that this looks like a FR re daily notes. However, I'd prefer to use this workflow instead of others as this is more flexible (adding after a heading, f.i.)

### Checklist

- [X] Feature Requests regarding daily notes unfortunately will not be implemented, since I do not use daily notes myself and there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin (please also explain why).

**Comment by chrisgrieser** [comment]
Actually, a recent refactoring, which was necessary to resolve an upstream issue, had to remove the ability to use dynamic placeholders anywhere in workflow. 

And you are right, this is indeed a bit of an daily note related request. Calculating date-related things is a whole different thing, and I think it'd make more sense for an already date-related workflow to add the capability of adding after a heading, instead of this workflow adding the ability to add to dynamic paths.  Sorry!
