### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by younuk23** [chrisgrieser/shimmering-obsidian#114]
### Feature Requested

Hello,

I have been using Alfred and Obsidian very effectively, and I am very satisfied with this workflow. I would like to make a suggestion while I was looking at the Feature Overview.

There is a Core Plugin called RandomNote in Obsidian. This feature allows you to open a random note in the Vault, and I would like it if this could be easily opened as a command in Alfred.

Thank you for creating this workflow, and I look forward to your consideration of my proposal.

Best regards,
younuk23

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Thanks for the kind words!

You do not need this Alfred workflow for that, since you can actually create such an Alfred keyword by yourself. Add this URL as custom search:
```
.obsidian://advanced-uri?commandid=random-note
```

<img width="660" alt="Pasted image 2023-02-03 16 37 12" src="https://user-images.githubusercontent.com/73286100/216643989-75ecf4a2-28ff-42b8-aaa3-455a925b1d29.png">

requires the advanced uri plugin.

**Comment by younuk23** [comment]
@chrisgrieser Thanks for the kind reply :)
