### ISSUE TITLE
Feature Request: Search within text (not only headers or tags)

### ISSUE THREAD

**Issue by Juul1** [chrisgrieser/shimmering-obsidian#120]
### Feature Requested

It would be nice to search within the standard text (besides headers or tags). Is this a possibility or are there any limitations?

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
It is possible to implement that, however, there are plugins like [omnisearch](https://obsidian.md/plugins?id=omnisearch) which do that already; and since plugins have access to far more Obsidian APIs than a third-party app like Alfred, they are also able to do that in a far more useful manner.

I have thought about it, but I honestly to not see much value in implementing a full search inside Alfred (see the last item of the checklist), sorry.

**Comment by Juul1** [comment]
Thanks for your quick and clear answer and of course for the great Alfred workflow 👍
