### ISSUE TITLE
Feature Request: Revisit Periodic Notes Support?

### ISSUE THREAD

**Issue by weklund** [chrisgrieser/shimmering-obsidian#161]
### Feature Requested

I recently started using this workflow (and Obsidian) and I'm trying to find a way to navigate to daily/weekly/etc notes using Alfred.  

Would we be willing to entertain period notes feature support again?  I see you've already covered this in a previous request: https://github.com/chrisgrieser/shimmering-obsidian/issues/45

I actually discovered https://github.com/hauselin/obsidian-alfred before this repo, and have forked and already fixed a few bugs on my own.  Having to do lots of refactoring and clean up.

Reasons to revisit:
1. Appears `hauselin/obsidian-alfred` is stale/dead? and hasn't responded to my pings.
2. Discovered several bugs in addition to stale issues that's currently blocking a working solution for Obsidian users
3. I'm happy to own and PR the feature since I've already implemented daily & weekly
          - I would prefer to use your code patterns than do refactoring on a fork
4.  I would like to add a pattern for having common javascript functions, and unit tests for them in CI.  Why?  I end up duplicating a lot of functions, so would like to consider using another file as a [Library](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/Importing-Scripts) - Jumping into JXA for the first time so happy to use a better mechanism if one exists.

I have several design questions before I would begin the feature, and happy to write up thoughts to get alignment.

Thanks!

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Hi, yeah, the main reason for deprecating anything daily- or weekly note related was that they are quite high maintenance (tons of different formats, a lot of date-related edge cases, etc.), while at the same time, I don't use daily notes at all.

If you are willing to PR and maintain the feature, I don't mind adding support for them again. 🙂 

> I would like to add a pattern for having common javascript functions, and unit tests for them in CI. Why? I end up duplicating a lot of functions, so would like to consider using another file as a Library - Jumping into JXA for the first time so happy to use a better mechanism if one exists.

To be honest, using JXA wasn't the best solution in hindsight. I started creating the workflow when I started out to learn programming, just used JXA because it was JavaScript that I could use without installing anything on my Mac. Due to the fact that a lot of code was written when I was just starting to learn to code, there are probably quite a few places with rather badly written code from that time 😅 

One of the big issues is that JXA does not support`import`, kinda restricting you to one file. It is mostly due to Alfred connecting different pipes, that the workflow nevertheless is modularized into different files – however, there is virtually no sharing of common functionality between the files, and therefore a good amount of redundant code. I was actually considering migrating the code base to typescript at some point, but I wasn't aware of those script libraries you linked. If they indeed allow for proper shared functionality, that'd be awesome.

**Comment by weklund** [comment]
> If you are willing to PR and maintain the feature, I don't mind adding support for them again. 🙂

Sweet!  Is this thread a good place to review with you my approach, proposed feature, and shortkeys?

Also do you have a good release version I can check out for the previous daily note feature?

> I was actually considering migrating the code base to typescript at some point in the future, but I wasn't aware of those script libraries you linked. If they indeed allow for proper shared functionality, that'd be awesome.

I'll do a quick POC and make sure it's what we want, but from the docs it _appears_ like a good way to share functionality across the code base.

**Comment by chrisgrieser** [comment]
> Sweet! Is this thread a good place to review with you my approach, proposed feature, and shortkeys?

Nah, issues are more "user-facing" so to speak. Think a (draft) PR might make most sense, I think.

> Also do you have a good release version I can check out for the previous daily note feature?

Don't think it's gonna help much. Those daily note features were from a time when the workflow was structured very differently, so it'd be hard to move just part of them to the present. Also, they were pretty bare bones "create file with today's date and append to it" anyway.
