### ISSUE TITLE
Bug: Quicklook not working with Peek app 

### ISSUE THREAD

**Issue by LYTWilson** [chrisgrieser/shimmering-obsidian#171]
### Feature Requested

I've read the docs and bought the app peek, hoping that the preview could work beautifully. When using it with general file searching in Alfred or in finder, it works great. However, it doesn't work only when using the shimmering obsidian file search. 

Below is a video explaining that: https://we.tl/t-Wxgx0K9PPL

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Hmm, I am using Peek as well and it works fine for me, so I don't really know how to change that.

Also, if you are reporting a bug, please use the bug report form, since it asks for various kinds of information needed to solve such an issue. For instance, in this case, I'd need the content of the debugging log (as described in the bug report form), to be able to do anything about it.

**Comment by LYTWilson** [comment]
Sorry it was my mistake of using the workflow, it works fine now! Should I delete this post now?

**Comment by chrisgrieser** [comment]
No, all good, we can simply close this
