### ISSUE TITLE
Feature Request: Add "New Unique Note" keyword 

### ISSUE THREAD

**Issue by jwmann** [chrisgrieser/shimmering-obsidian#172]
### Feature Requested

Obsidian has a core plugin called "Unique Note Creator" which has built-in commands to create a new unique note.

Since we already have `on` for regular notes, it would super useful if I we could create a unique note similarly through Alfred.
Perhaps the keyword could be: `onu`

Thoughts?

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
Hi,

I am trying to avoid adding features that require specific plugins, since they are likely to only benefit a few users who actually use those plugins.

However, what you request is actually pretty easy to create yourself in Alfred without having to write any code at all – you can use the Advanced URI plugin to create a URI to run any command. Then you create a new workflow and have a keyword that opens that workflow.

Here I have created a simple example for triggering the Unique Note Creator via `onu`: [Alfred workflow to run a Command in Obsidian.zip](https://github.com/chrisgrieser/shimmering-obsidian/files/15043008/Run.a.Command.in.Obsidian.zip)

Hope that helps!

**Comment by jwmann** [comment]
> Hi, I am trying to avoid adding features that require specific plugins, since they are likely to only benefit a few users who actually use those plugins.
> 
> However, what you request is actually pretty easy to create yourself in Alfred without having to write any code at all – you can use the Advanced URI plugin to create a URI to run any command. (`Advanced URI: Copy URI for command` → `<Don't specify a file>` → Select the command you want to run.) Then you create a new workflow and have a keyword that opens that workflow.
> 
> Here I have created a simple example for triggering the Unique Note Creator via `onu`: [Alfred workflow to run a Command in Obsidian.zip](https://github.com/chrisgrieser/shimmering-obsidian/files/15043008/Run.a.Command.in.Obsidian.zip)
> 
> Hope that helps!

This demo workflow is perfect, thanks for the tips! 👍
