### ISSUE TITLE
Feature Request: Sort results by file name > H1 > H2 > H3

### ISSUE THREAD

**Issue by saeedesmaili** [chrisgrieser/shimmering-obsidian#173]
### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If you are looking for a way to trigger a specific Obsidian command from outside Obsidian, [see this comment explaining how you can easily create such a workflow yourself.](https://github.com/chrisgrieser/shimmering-obsidian/issues/172#issuecomment-2066890678)

### Feature Requested

I would like to dial some knobs to tell the workflow to give more weight to the file name, then H1, then H2, then H3. When I search for `photography` and I have a note with `photography` as file name, I'd like to see it first in the results:
<img width="719" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/13351748/ea02b0fb-d837-4c0a-bbfd-581ea883e428">

Having some sort of weight adjustments like Obsidian Omnisearch plugin would be fantastic:
<img width="783" alt="image" src="https://github.com/chrisgrieser/shimmering-obsidian/assets/13351748/af63aea1-3df2-41e8-8bf0-38e2e3afcc71">

### Alternatives considered

I'm using this alfred workflow probably 50-60 times a day, and I encounter this issue a lot, and I've been just trying to find the item (file name) in the results and clicking on it or using cmd+number.

**Comment by chrisgrieser** [comment]
Such fine-grained weighting of results is unfortunately not possible with Alfred. (Allowing for something like that would be an Alfred Feature Request, which I'd gladly upvote if you posted it in the Alfred forum.)

However, I can see that the heading search is far from optimal. I changed the matching behavior, so that heading searches only match the heading content, not the file content (meaning in your example, only H1 and the file would be matched, and not all the other headings). This should reduce most of the noise and is unfortunately the most I can do on my end.

https://github.com/chrisgrieser/shimmering-obsidian/releases/download/4.6.0/shimmering-obsidian.alfredworkflow

**Comment by saeedesmaili** [comment]
I think that's still a big improvement! Thank you.

**Comment by chrisgrieser** [comment]
glad it helps!
