### ISSUE TITLE
Feature Request: Create my own workflow to prepend specific docs?

### ISSUE THREAD

**Issue by jamie9090** [chrisgrieser/shimmering-obsidian#193]
### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#table-of-contents) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If you are looking for a way to trigger a specific Obsidian command from outside Obsidian, [see this comment explaining how you can easily create such a workflow yourself.](https://github.com/chrisgrieser/shimmering-obsidian/issues/172#issuecomment-2066890678)

### Feature Requested

Hello!

I would love to be able to repurpose the prepend functionality of the workflow to be able to set my own triggers.

Example:
1. todo query --> Prepend the "To Do" note
2. idea query --> Prepend the "Ideas" note
3. learning query --> Prepend the "Journal" note

Open to all solutions here.

I could see this being of value to all types of users who often edit the same notes often

### Alternatives considered

Currently I use Obsidian QuickAdd for this, but that has its own limitations.

**Comment by chrisgrieser** [comment]
Setting your own triggers for various stuff unfortunately isn't something that is easy to do in a way that is customizable for users. Also, I feel like this is too nice of a feature to be honest, sorry. 

What you can do is either append using the main search. 

Alternatively, you can create your own simple workflow for this, since obsidian notes are just pain text files you can interact with. Alfred allows you to do that without having to write any code. See the Alfred docs for that.
