### ISSUE TITLE
Date format for shimmering Obsidian

### ISSUE THREAD

**Issue by manfrombar** [chrisgrieser/shimmering-obsidian#23]
I have defined in my Obsidian Daily notes YYYY-MM-DD dddd, that it shows 2021-11-16 Tuesday.
I have tried to modify the Alfred workflow to the default date format but It doesn't work. Can you help me?

**Comment by chrisgrieser** [comment]
since there seems to be a lot of interest into daily notes improvements, I'll tackle the subject daily notes probably next. I'll add customization then.

**Comment by chrisgrieser** [comment]
I am sorry to say that I feel a bit uneasy to work on and maintain the daily note feature – since I personally do not use daily notes myself, I would have to rely on someone else to maintain this, which probably isn't worth the effort. However, the [Alfred workflow by hauselin](https://github.com/hauselin/obsidian-alfred) does focus a lot more on daily note features, and can be used alongside this workflow without any issue. 

Therefore, I think it makes more sense to make a feature request for that hauselin's workflow.
