### ISSUE TITLE
Feature Request: in alfred, directly type name and find obsidian notes without typing "o" prefix

### ISSUE THREAD

**Issue by posedonius** [chrisgrieser/shimmering-obsidian#37]
i added to alfred scope: look for .md filetypes inside my vault folder, so if i start typing the name of an obsidian note, i can see the .md note come up, but it doesnt want to open in osbidian, despite changing the "always open with obsidian.app" option in mac os "get info".  wondering if this can be done with additional scripting in alfred?  thank you.

**Comment by chrisgrieser** [comment]
Because Obsidian can only open files inside a vault, it cannot be used as an app to open a markdown file, even if you set it like that in mac OS.

However, [someone posted a solution in the forums](https://forum.obsidian.md/t/make-obsidian-a-default-app-for-markdown-files-on-macos/22260) that that will open a markdown file inside a vault in Obsidian via URL Scheme and all other markdown files with a different app. This is probably the solution you are looking for. :)

Otherwise, I am closing this, since this issue is related to macOS in general and not this workflow.

**Comment by posedonius** [comment]
"Obsidian can only open files inside a vault..."

ahh i didnt realize that, thanks for explaining and for the other solution link.
