### ISSUE TITLE
[BUG] Usage of iCloud vault with Workflow

### ISSUE THREAD

**Issue by KingOfSpades** [chrisgrieser/shimmering-obsidian#41]
**Describe the Bug**
When using the workflow with a vault in iCloud multiple error's and crashes occur.

**To Reproduce**
1. Install Workflow
2. Run Setup
3. Choose vault located in iCloud
4. Use any function, example `ot`

**Relevant Screenshots**
![CleanShot 2021-12-27 at 09 32 27](https://user-images.githubusercontent.com/2156115/147452730-1f1629f6-a916-40ba-906d-05446b578f58.gif)

**Is the Problem related to Obsidian 0.13+ / Live Preview Mode?**
No

**Debugging Log**

```
logdata
[09:32:30.348] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[09:32:30.569] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[09:32:30.770] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[09:32:30.772] ERROR: Shimmering Obsidian[Script Filter] Code 1: /Users/USERNAME/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6F61475A-ADFF-40EE-9918-7345A9ECF86C/scripts/tag-search.js: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
```

**Checklist**
- [x] I have updated to the latest version of this workflow, the Advanced URI plugin, and the Metadata Extractor plugin.
- [x] I have read and checked the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [x] I read the [Breaking Changes Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Breaking%20Changes.md) to make sure the unexpected behavior is not a breaking change.

**Comment by chrisgrieser** [comment]
The Workflow works inside iCloud, my own vault is in iCloud.

According to the debugging log, you are missing the metadata created by the Metadata Extractor plugin. Since you are mentioning "a vault in iCloud", my guess is that you are using the workflow in a second vault now?

If that is the case, you need to install the metadata extractor and the advanced URI plugin in the second vault as well & run `osetup` once in the second vault, too. After that, it should work.
