### ISSUE TITLE
[Bug]: The ⇧ ⏎ command closes the Alfred window without allowing for link browsing

### ISSUE THREAD

**Issue by seishonagon** [chrisgrieser/shimmering-obsidian#49]
### Bug Description

If I search for a note using "o", then press ⇧ ⏎, the Alfred window closes without opening the note nor giving me the list of links in the note.

If I search for the same note, open it, then use the "ol" keyword, I get the expected list of links.

### Relevant Screenshot

Search for a note: 
<img width="737" alt="CleanShot 2022-01-22 at 21 38 09@2x" src="https://user-images.githubusercontent.com/6635078/150654943-0da99817-223e-4fdf-890f-c22f106087d9.png">

Use "ol"
<img width="751" alt="CleanShot 2022-01-22 at 21 41 05@2x" src="https://user-images.githubusercontent.com/6635078/150654964-47a345ef-1dbe-4640-9018-cd0a7ed0ed5c.png">

List of links is ok:
<img width="742" alt="CleanShot 2022-01-22 at 21 41 40@2x" src="https://user-images.githubusercontent.com/6635078/150654974-0bd7ca40-fdb6-4756-ae4a-fcd26745afd9.png">

If I use "o" to search and then press ⇧ ⏎, nothing happens (no screenshots, because the window just closes

### To Reproduce

Happens every time. 

### Debugging Log

[21:44:02.547] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[21:44:02.813] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[21:44:02.816] Shimmering Obsidian[Script Filter] [truncated]
[21:44:10.757] Shimmering Obsidian[Script Filter] Processing complete
[21:44:10.758] Shimmering Obsidian[Script Filter] Passing output 'notes 📒/9. Work 📈/91 Spaces/910 Projects/KEEN/KEEN.md' to Call External Trigger
[21:44:10.758] Shimmering Obsidian[External] Processing complete
[21:44:10.759] Shimmering Obsidian[External] Passing output 'notes 📒/9. Work 📈/91 Spaces/910 Projects/KEEN/KEEN.md' to Write Text File
[21:44:10.760] Shimmering Obsidian[Write Text File] Processing complete
[21:44:10.760] Shimmering Obsidian[Write Text File] Passing output '/Users/paul/Library/Application Support/Alfred/Workflow Data/de.chris-grieser.shimmering-obsidian/buffer_inputPath' to Arg and Vars
[21:44:10.760] Shimmering Obsidian[Arg and Vars] Processing complete
[21:44:10.761] Shimmering Obsidian[Arg and Vars] Passing output '' to Script Filter
[21:44:10.775] Shimmering Obsidian[Script Filter] Queuing argument '(null)'

### Workflow Configuration

<img width="494" alt="CleanShot 2022-01-22 at 21 44 49@2x" src="https://user-images.githubusercontent.com/6635078/150655035-56f19e27-b8d7-4387-80a2-58cdec6d3d57.png">

### Version & System Information
```
-------------------------------
Metadata JSONs: 3/3
-------------------------------
INSTALLED VERSION
macOS: 12.1
Obsidian: 0.13.21
Alfred: 4.6.1
Workflow: 2.18.2
Advanced URI Plugin: 1.17.0
Metadata Extractor: 0.2.4
-------------------------------
LATEST VERSION
Obsidian: 0.13.19
Obsidian (Insider): 0.13.21
Workflow: 2.18.2
Advanced URI Plugin: 1.17.0
Metadata Extractor: 0.2.4
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [X] If the `o ...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by chrisgrieser** [comment]
`ol` working, but `shift + return` not working is indeed weird, since both commands literally use the same function 🧐 

okay, so here is what we can do:
1. Try running `osetup` and try again. 
2. Since your environment variables show that you have been using the workflow since version 1.x, you should try uninstalling and then re-installing the workflow. for some reasons, there seems to be an Alfred bug not properly updating the workflow for users who have been using 1.x at some point int he past. (remember to save your configs before uninstalling/deleting the workflow, since they won't be saved upon uninstalling the workflow.) 

After installing, run `osetup` once and try again whether `shift + return` works.

3. If it still does not work, I need some more debugging infos. So select a note with non-private information which you are comfortable to share, and then attach the following:
  - get the debugging log where you run `ol` (and it works)
  - get the debugging log for when you run the `o` command, search for the note, and select it with `shift + return` (where it not works.)
  - the note itself you selected

upload all three as files (since pasting them would be quite long, since your vault is so big :P )

**Comment by seishonagon** [comment]
Hi, thanks for the quick reply!
So osetup was NOT running, there was indeed a bug in the update. However, after uninstalling, reinstalling, I still have the same problem. 
Here's a note, the log of the ol command working, and the note of the shift enter command not working. 
Hope you can make sense of it!

[Foot soldiers in the culture wars.md](https://github.com/chrisgrieser/shimmering-obsidian/files/7919795/Foot.soldiers.in.the.culture.wars.md)
[ol working.txt](https://github.com/chrisgrieser/shimmering-obsidian/files/7919798/ol.working.txt)
[search shift enter not working.txt](https://github.com/chrisgrieser/shimmering-obsidian/files/7919805/search.shift.enter.not.working.txt)

Thanks...

**Comment by seishonagon** [comment]
On a related (?) note, the "ot" keyword doesn't work either. 
I type "ot", get a list of tags. 
And if I type "enter" on a tag ... Alfred window closes and nothing happens.

**Comment by patowod** [comment]
I have the same issues as @seishonagon.

**Comment by chrisgrieser** [comment]
Could you two attach the files located in the following folder? It's basically the workflow's cache-folder and used for both `ol` and `ot`.

```
~/Library/Application Support/Alfred/Workflow Data/de.chris-grieser.shimmering-obsidian/
```

---

> So `osetup` was NOT running, there was indeed a bug in the update. However, after uninstalling, reinstalling, I still have the same problem.

what do you mean by that? did the command `osetup` not work, and after re-installing it did?

**Comment by seishonagon** [comment]
Sorry, I wasn't clear. I meant 
1) you were right. There was an upgrade problem. osetup was not a keyword I could use in my installation. I deleted everything, reinstalled the latest version, reset the configuration .....

2) osetup now works: it asks me which vault I want to use (i'm assuming it's all the interaction I need to have with it?)


3) despite the reinstallation, the issue still exists.

Here are the files you asked for: [de.chris-grieser.shimmering-obsidian.zip](https://github.com/chrisgrieser/shimmering-obsidian/files/7920876/de.chris-grieser.shimmering-obsidian.zip)

the values correspond to the last searches in ol and in ot

**Comment by chrisgrieser** [comment]
okay, this was was tricky, but I think I may have found a solution. Could you two try updating to 2.18.4 and check whether it works now?

**Comment by patowod** [comment]
@chrisgrieser I looked at the path you posted. Within I only have to files which both have merely one line as content.

- buffer_inputPath contains "Highlights/How to Be a Stoic.md"
- buffer_selectedTag contains "highlights"

**Comment by seishonagon** [comment]
sorry, despite install and restart, same issue.

**Comment by patowod** [comment]
Same here. I also  updated to 2.18.4. buffer_inputPath and buffer_selectedTag still contains only one line which is the last tag I tried to action through ot. 

One thing I noticed is that ol does work if the corresponding note is open but not if I locate it via o and try shift return. But I think this was also stated initially. Anything else we can provide?

**Comment by seishonagon** [comment]
Here is a weird thing I've noticed:

In the workflow itself, there is this action : 
<img width="942" alt="CleanShot 2022-01-23 at 19 01 36@2x" src="https://user-images.githubusercontent.com/6635078/150691644-58ea59b1-a5eb-418f-804f-2bcbfe8eeca9.png">

It describes - I think - what happens if I press "o " and then start typing. If I then press "⇧", the subtext that appears in obsidian is "⇧: Browse Links In Notes"  ... emphasis on the **IN**.
BUT, the text that's in that workflow is 
<img width="823" alt="CleanShot 2022-01-23 at 19 04 46@2x" src="https://user-images.githubusercontent.com/6635078/150691764-03872628-b01b-429e-81ab-96a288093fdc.png">

That reads "⇧: Brow Links of Notes" .... **OF**, not **IN** 
If I change that text to something recognizable (i've added some emojis), it's still NOT the one that appears with the "o " command. 

So at a guess, the trigger "o " does NOT call this particular bit of workflow but something else, where you've typed IN, not OF.

Maybe this helps?

**Comment by chrisgrieser** [comment]
> That reads "⇧: Brow Links of Notes" .... OF, not IN

nice of you to check, but unfortunately, that one is entirely irrelevant, it's only some leftover text, the subtitle is now generated via script and not that text field 🙈 

> I also updated to 2.18.4. buffer_inputPath and buffer_selectedTag still contains only one line which is the last tag I tried to action through ot.

In fact, when the buffer only contains exactly one line, then everything is actually working fine.

--- 

so here is the problem; there is nothing in the error logs indicating a problem. Using your example file, everything works fine on my end. The buffer also indicates no problem. I use the same version of Alfred and MacOS, so that also cannot be the problem. So since I cannot reproduce the problem, this leaves pretty much guess work on my end. 

What is weird about this is that the `ol` command and the `o` command with `shift + return` both use exactly the same function, and the very same buffer. So it is really puzzling to me, why one of them works and the other doesn't. However, it appears to be a buffer issue, since the only thing `ot` and `ol` have in common is that they are the only commands of this workflow using a buffer.

So I have released version 2.18.6, which creates a workaround in unlikely the case this issue is a bug related to Alfred buffer-writing function. 

Otherwise, the release adds a buffer-logging function, this means the changes in the buffer will be logged in the file `~/Library/Application Support/Alfred/Workflow Data/de.chris-grieser.shimmering-obsidian/buffer_log`. 

Please try to run `ol`, and afterwards run `o`, search for the very same file currently open, press `shift + return`. Repeat that process 3-4 times with different files. Then, post the content of `buffer_log` here. If there is a problem with the buffer, it should be noticeable in that log file.

**Comment by patowod** [comment]
Hi, just a quick update on the contents of buffer_log below. What I find very interesting, is that whatever you did it led to the command ot working and showing the notes corresponding to that tag when actioning it with return. 🎉

Contents of a quick buffer_log
---
[ol]             Highlights/How to Be a Stoic.md
[ol]             Highlights/How to Be a Stoic.md
[shift + return] Highlights/How to Be a Stoic.md
[ol]             200619100611 Methods.md
[ol]             Highlights/Immer Mehr Ist Immer Weniger.md
[shift + return] Highlights/Immer Mehr Ist Immer Weniger.md
[tag]            todo
[tag]            review

**Comment by chrisgrieser** [comment]
> whatever you did it led to the command ot working and showing the notes corresponding to that tag when actioning it with return. 🎉

oh that actually means we have found an extremely hard to find bug in Alfred 🙈 But at least it's working now.

> [ol] Highlights/How to Be a Stoic.md
[shift + return] Highlights/How to Be a Stoic.md

So this shows that the buffer of both commands is exactly the same. And yet `ol` works but `shift + return` doesn't? ლ(ಠ_ಠლ)╯

**Comment by seishonagon** [comment]
Yep everything works and the buffers are the same ! And I just had a look at the changes between .5 and .6 - that's a lot of code. Thanks ever so much for the effort - on a Sunday.

**Comment by chrisgrieser** [comment]
yeah, it kept bothering me so much, that I got my head into it tbh 🙈 

But good that it works now!

**Comment by chrisgrieser** [comment]
@seishonagon Thanks for the coffee btw 🙏

**Comment by seishonagon** [comment]
👍

**Comment by Miaoyifei-mz** [comment]
@chrisgrieser Hello,  I have the similar problem when I want to browse folders, the Alfred window closes without opening the folder.

**Relevant Screenshot**
https://user-images.githubusercontent.com/60280844/163702460-7824d998-ba6c-4771-806e-7a018506e692.mp4

**To Reproduce**

Happens every time.

**Debugging Log**

```
[13:53:36.795] Shimmering Obsidian[Script Filter] Processing complete
[13:53:36.804] Shimmering Obsidian[Script Filter] Passing output '3-日记' to Call External Trigger
[13:53:36.805] Shimmering Obsidian[External] Processing complete
[13:53:36.805] Shimmering Obsidian[External] Passing output '3-日记' to Arg and Vars
[13:53:36.806] Shimmering Obsidian[Arg and Vars] Processing complete
[13:53:36.806] Shimmering Obsidian[Arg and Vars] Passing output '3-日记' to Arg and Vars
[13:53:36.806] Shimmering Obsidian[Arg and Vars] Processing complete
[13:53:36.807] Shimmering Obsidian[Arg and Vars] Passing output '3-日记' to Conditional
[13:53:36.807] Shimmering Obsidian[Conditional] Processing complete
[13:53:36.807] Shimmering Obsidian[Conditional] Passing output '3-日记' to Call External Trigger
[13:53:36.808] Shimmering Obsidian[External] Processing complete
[13:53:36.808] Shimmering Obsidian[External] Passing output '' to Script Filter
[13:53:36.809] Shimmering Obsidian[Script Filter] Queuing argument '(null)'

```

**Version & System Information**

```
-------------------------------
Metadata JSONs: 3/3
-------------------------------
INSTALLED VERSION
macOS: 12.3.1
Obsidian: 0.14.5
Alfred: 4.6.3
Workflow: 2.22.1
Advanced URI Plugin: 1.21.1
Metadata Extractor: 1.0.1
-------------------------------
LATEST VERSION
Obsidian: 0.14.5
Obsidian (Insider): 0.14.6
Workflow: 2.22.3
Advanced URI Plugin: 1.21.1
Metadata Extractor: 1.0.1
-------------------------------
```

**Comment by Miaoyifei-mz** [comment]
Sorry, I found myself using an outdated version. I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow and run `osetup` . But the problem still persists.

**Comment by chrisgrieser** [comment]
@Miaoyifei-mz There seems to be some issues on Alfred's side with updating workflows that have changed a lot. Could you try completely removing the workflow and then installing it anew with the latest version?

If that does not help, please open a new bug report as a new issue, since I suspect a different cause and since the bug report form does ask for various types of information I will need from you for debugging.
