### ISSUE TITLE
[Bug]: Tag searching incorrect. #gui also returns #guitar results

### ISSUE THREAD

**Issue by MartijnDB** [chrisgrieser/shimmering-obsidian#53]
### Bug Description

This is due to the fact that 'Alfred filters results' is used. 
So not directly a bug, but also not expected behavior.

### To Reproduce

Type: o #gui
Type: o #guitar

### Debugging Log

-

### Workflow Configuration

-

### Version & System Information

```text
This command has no results in Alfred.
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/Troubleshooting.md).
- [X] If the `o ...` main search does not work, I have tried rerunning `osetup` and it still does not work.

**Comment by chrisgrieser** [comment]
well, I'd say that is the intended behavior, so I'd rather label this as a feature request.

The `o` search is supposed to be a *quick* search, and having to fully type out a tag does diminish that quickness slightly. In addition,  as you noted yourself, that is also due to the fact that I let Alfred filter the search results, because it has a much better performance. 

When you want *solely* notes with the tag "#gui" but not "#guitar", that's what the tag-based search (`ot`) is for. 

So all in all, implementing a non-Alfred filter would be a) a pretty big rewriting, b) decrease the main search performance, c) make it slower when you really only want to quickly access a note, and d) only improve a rather edge case for which is actually covered by a more specialized feature. Therefore, I think this is not something that I'd implement. 

But as I said, the `ot` search should already solve your problem 🙂

**Comment by MartijnDB** [comment]
It’s not exactly a bug indeed, I just wanted to let you know though.

Because the ot search is nice, but does not allow for searching multiple tags. 

Anyway, keep up the good work! I love the workflow 😍

**Comment by chrisgrieser** [comment]
Thanks!

Ah multi-tag search is indeed sth not covered properly. M Could you open a or for it? Then Ill see that I implement it the next time I am working on it :)
