### ISSUE TITLE
Change date and time format via variables

### ISSUE THREAD

**Issue by hnsol** [chrisgrieser/shimmering-obsidian#6]
Thank you for providing a great workflow. Notably, the OCR-screenshot function impressed me so much!!

Is there any chance for considering that the date and time format can be changed (maybe using variables)?

Since the default Date and Time Placeholders `{date:full}, {time:medium}` 
are very annoying for Japanese users. In my case, I use `{date:yyyy-MM-dd} {time:HH:mm}`.

<img src="https://i.gyazo.com/b898aa77e8be2ce37bbf1f421d28ba6a.png" width=40%>

Although I can replace it manually for every release, I would be grateful if you could consider way for changing.

<img src="https://i.gyazo.com/2980df3b929d86f0dffa843d111563fc.png" width=40%>

Regards,

**Comment by chrisgrieser** [comment]
> Thank you for providing a great workflow. Notably, the OCR-screenshot function impressed me so much!!

Thanks! I heard from a lot of people that the OCR function is most useful to them, which feels ironic since all other features required so much more time to implement 😅

> Since the default Date and Time Placeholders {date:full}, {time:medium}
are very annoying for Japanese users. In my case, I use {date:yyyy-MM-dd} {time:HH:mm}.

Good point. Done so in [release 1.3.2](https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/1.3.2).
