### ISSUE TITLE
Support for multiple Vaults?

### ISSUE THREAD

**Issue by m0ll3art** [chrisgrieser/shimmering-obsidian#63]
Hi. 

first tremendous job :clap: really enjoy your workflow. I am just beginning to use it and I was asking myself if the Workflow supports searching in multiple vaults?

Indeed, I tend to use multiple vaults and was experimenting with the scratchpad, but it seems that for opening or appending to the scratchpad only one Vault is supported, namely the one set up by `osetup` command. 

The question is if the workflow would be able to search in multiple vaults, of course having the 2 external prereq Plugins installed?  I really only need to search through my notes and open them in Obsidian. For the rest, I prefer to manage my notes (C_R_UD) in their respective vaults 
thanks

**Comment by chrisgrieser** [comment]
You can already switch between vaults that are controlled by this workflow [with the vault switcher command `ov`](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Vault%20Switcher.md). 

Searching/controlling two vault's *simultaneously* is technically possible, but the implementation would require a lot of work for a rather small benefit, so I am sorry to say that I most likely won't implement that. Multi-Vault-Search is something that should be implemented by an obsidian plugin, tbh, since there is no real benefit from implementing that via Alfred over Obsidian itself, in my view.
