### ISSUE TITLE
"on" fails in 1.3.2

### ISSUE THREAD

**Issue by nwehrle** [chrisgrieser/shimmering-obsidian#7]
Message:
<img width="250" alt="Screenshot 2021-08-29 at 19 21 16" src="https://user-images.githubusercontent.com/832234/131259456-05b5534a-7b6f-4cf0-8419-c31a1a7055f9.png">

Log:
<img width="531" alt="Screenshot 2021-08-29 at 19 22 33" src="https://user-images.githubusercontent.com/832234/131259473-28aaa83f-0d40-4cc1-a9a0-66664866d548.png">

Config:
<img width="805" alt="Screenshot 2021-08-29 at 19 23 13" src="https://user-images.githubusercontent.com/832234/131259495-467edf42-9a7a-49e8-ac45-9450afafb084.png">

OS: 
<img width="200" alt="Screenshot 2021-08-29 at 19 23 49" src="https://user-images.githubusercontent.com/832234/131259508-101e0537-88f7-4b50-a278-a83e56940021.png">

**Comment by nwehrle** [comment]
If I switch use_quickadd to "false", "ON" works, but "ODUAL" does not.

**Comment by nwehrle** [comment]
*If* it works, I see this behaviour:
Obsidian not open: "odual" simply starts with he last note
Obsidian already open: "odual" opens the unlinked preview
Obsidian already open in preview mode: "odual" opens additional unlinked preview

Is this intended? I would expect this:
Obsidian not open: "odual" starts with he last note in edit and preview mode
Obsidian already open in edit mode: "odual" opens the **linked** preview
Obsidian already open in preview mode: "odual" opens the **linked** editor

**Comment by chrisgrieser** [comment]
- The trouble with using `on` with QuickAdd *while Obsidian is not running* is a combination of circumstances I actually did not test. It should be fixed now with [release 1.4](https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/1.4).
- Using `odual` while Obsidian is *not running* is indeed a use case I did not really consider, as I personally would not remember which was the last open file. 😛  Nevertheless, it should be fixed with release 1.4 as well.
- Opening the new pane as linked pane is not possible right now, [as Obsidian does not expose that function via command palette](https://forum.obsidian.md/t/open-a-note-in-a-new-pane-using-the-command-palette-or-a-keyboard-shortcut/23303). `odual` is therefore only able to open the an *unlinked* pane.
- Concerning `odual` while the note is in preview mode: Unfortunately, this is also not possible as Obsidian also does not expose information on the current view mode to outside apps. So basically, it only works while you are in edit mode. I added this piece of info to the documentation.

As I think all issues are covered, I'll close this issue – if I missed something, feel free to create a new one 🙂 
(Thanks for the donation, btw 🤗 )

**Comment by nwehrle** [comment]
Thank you for your fast and Comprehensive reply.

"odual" would suddenly make a lot more sense, if you could give it the file to be opened as a parameter.
"on" would also win with a parameter.

**Comment by chrisgrieser** [comment]
[Done.](https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/1.5) 🙂 
(I implemented your suggesting for `odual` as a modifier key for `o` and `os` though, as simply passing a note name to `odual` would not work well.)

**Comment by nwehrle** [comment]
Thank you. Really like, that your impl is always one step further than the initial suggestion.

**Comment by chrisgrieser** [comment]
> Concerning `odual` while the note is in preview mode: Unfortunately, this is also not possible as Obsidian also does not expose information on the current view mode to outside apps. So basically, it only works while you are in edit mode. I added this piece of info to the documentation.

I stand corrected – I did found a different view to check view mode: Obsidian stores them in `.obsidian`! S I _did_ implement this in [release 1.5.3](https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/1.5.3) :)
