### ISSUE TITLE
[Docs]: Add instructions to install Tesseract for OCR

### ISSUE THREAD

**Issue by solidgonk** [chrisgrieser/shimmering-obsidian#93]
### Change Requested

OCR requires Tesseract, which can be installed using [HomeBrew](http://brew.sh/):
`brew install tesseract`

### Link to the relevant section of the documentation

https://github.com/chrisgrieser/shimmering-obsidian#Workflow-Installation

**Comment by chrisgrieser** [comment]
Instructions for installing tesseract [are already included in the docs here](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Screenshot%20Features.md#requirements).

I tried to keep the initial setup as easy as possible, since most users will not actually use the OCR screenshot feature.
