### ISSUE TITLE
[Bug]: Can't add note into daily notes in new version

### ISSUE THREAD

**Issue by chumido98** [chrisgrieser/shimmering-obsidian#97]
### Bug Description

In old version, i can add tasks in daily note with od keyword, but now i can't do it in new version

### Relevant Screenshot

![Uploading CleanShot 2022-09-14 at 09.17.06@2x.jpg…]()

### Debugging Log

```Text
I don't have
```

### Workflow Configuration

![CleanShot 2022-09-14 at 09 22 19@2x](https://user-images.githubusercontent.com/61721378/190044275-bdd33acc-5fdd-46eb-97d2-1b049700165a.jpg)

### Version & System Information

```Text
-------------------------------
Metadata JSONs: 3/3
Metadata String Length: 672459
-------------------------------
INSTALLED VERSION
macOS: 12.6
Alfred: 5.0.3

Obsidian: .asar file missing
This Workflow: 3.0.0
Advanced URI Plugin: 1.26.1
Metadata Extractor: 1.0.2
-------------------------------
LATEST VERSION
Obsidian: 0.15.9 (Insider: 0.16.2)
This Workflow: q
Advanced URI Plugin: 1.26.1
Metadata Extractor: 1.0.2
-------------------------------
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Troubleshooting.md).
- [X] If the `o...` main search does not work, I have tried rerunning `osetup` and it still does not work.
- [X] If I updated from version 2.27.x to 2.28+, I have properly checked out the new information in the workflow configuration and also tried restarting Alfred.

**Comment by chrisgrieser** [comment]
Since I do not use daily notes myself and cannot properly maintain the feature, I unfortunately have to remove the daily notes functionality (it has been deprecated for a while now). I simply don't find the time maintaining features that I do not use myself, but are time-intensive to work on. Especially since I am the sole maintainer of multiple repos.

I encourage you to check out the [Alfred workflow for Obsidian by hauselin](https://github.com/hauselin/obsidian-alfred), which focuses on daily notes and complements this workflow well.
