### ISSUE TITLE
Fuzzy match Vault name

### ISSUE THREAD

**Issue by suliveevil** [chrisgrieser/shimmering-obsidian#99]
### Feature Requested

Fuzzy match Obsidian vault name when use <kbd>ov</kbd> searching Obsidian vaults

### Relevant Screenshot

![截屏2022-09-29 05 55 27](https://user-images.githubusercontent.com/35763237/192897111-b716dbef-f432-4a22-a77c-a8cdeb95d0e7.png)

Didn't show `Chaos` vault:

![截屏2022-09-29 05 55 43](https://user-images.githubusercontent.com/35763237/192897228-4daa7261-341b-4530-a6c9-1077b311f041.png)

### Checklist

- [X] Feature Requests regarding daily notes unfortunately will not be implemented, since I do not use daily notes myself and there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin (please also explain why).

**Comment by chrisgrieser** [comment]
as much as I'd love to have that, that is unfortunately not possible with Alfred, since there is [no option for fuzzy-finding in the word-matching behavior](https://www.alfredapp.com/help/workflows/inputs/script-filter/#alfred-filters-results). You should open a Feature Request at the Alfred forum (which I'll gladly upvote if you link it here.)
